name: env Context
description: Add host environment variables to the env context
author: In Loco
inputs:
  mask:
    description: Environment variables to mask
    default: ''
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        for VAR in ${{ inputs.mask }}
        do
          echo "::add-mask::${!VAR}"
        done
    - shell: bash
      run: |
        awk 'BEGIN{for(v in ENVIRON) print v}' | while read e; do
          echo "$e<<EOF" >> $GITHUB_ENV
          echo "${!e}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        done
